spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/${H2_DATABASE_NAME}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driverClassName: org.h2.Driver
---
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

---
spring:
  sql:
    init:
      mode: always
