spring:
  profiles:
    active: dev
    include: aws
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    properties:
      generate-ddl: 'true'
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:

logging.level:
  org.hibernate.SQL: debug
